using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using GlassDFIR.Views;

namespace GlassDFIR.Controls
{
    public class FormattingRule
    {
        public string PropertyName { get; set; } = string.Empty;
        public string Value { get; set; } = string.Empty;
        public string ColorHex { get; set; } = "#f7768e"; // Default Red
    }

    public class GridSessionState
    {

        public List<ColumnState> Columns { get; set; } = new List<ColumnState>();
        public List<FormattingRule> FormattingRules { get; set; } = new List<FormattingRule>();
    }

    public class ColumnState
    {
        public string PropertyName { get; set; } = string.Empty;
        public double Width { get; set; }
        public int DisplayIndex { get; set; }
        public bool IsVisible { get; set; } = true;
    }

    public partial class AdvancedDataGrid : UserControl
    {
        public class DistinctValueItem : System.ComponentModel.INotifyPropertyChanged
        {
            private bool _isChecked;
            public string Value { get; set; } = "";
            public bool IsChecked 
            { 
                get => _isChecked; 
                set { _isChecked = value; OnPropertyChanged(nameof(IsChecked)); }
            }

            public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
            protected void OnPropertyChanged(string name) => PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(name));
        }

        private Point _dragStartPoint;
        private Dictionary<string, string> _columnFilters = new Dictionary<string, string>();
        private System.Windows.Threading.DispatcherTimer _filterDebounceTimer;
        private Dictionary<string, HashSet<string>> _distinctFilters = new Dictionary<string, HashSet<string>>();
        private List<DistinctValueItem> _currentDistinctItems = new List<DistinctValueItem>();
        private string? _currentFilterProperty;
        private bool _isUpdatingSelectAll;
        public ObservableCollection<FormattingRule> FormattingRules { get; } = new ObservableCollection<FormattingRule>();

        // Cache for reflection optimizations
        private static readonly Dictionary<Type, System.Reflection.PropertyInfo[]> _propertyCache = new Dictionary<Type, System.Reflection.PropertyInfo[]>();


        public static readonly DependencyProperty PersistenceKeyProperty =
            DependencyProperty.Register("PersistenceKey", typeof(string), typeof(AdvancedDataGrid), new PropertyMetadata(null, OnPersistenceKeyChanged));

        public string PersistenceKey
        {
            get => (string)GetValue(PersistenceKeyProperty);
            set => SetValue(PersistenceKeyProperty, value);
        }

        private static void OnPersistenceKeyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is AdvancedDataGrid control)
            {
                // Save old state if we had a key
                if (e.OldValue is string oldKey && !string.IsNullOrEmpty(oldKey))
                {
                    _ = control.InternalSaveStateAsync(oldKey);
                }

                // Load new state
                control.LoadState();
            }
        }

        public static readonly DependencyProperty ItemsSourceProperty =
            DependencyProperty.Register("ItemsSource", typeof(IEnumerable), typeof(AdvancedDataGrid), new PropertyMetadata(null, OnItemsSourceChanged));

        public IEnumerable ItemsSource
        {
            get => (IEnumerable)GetValue(ItemsSourceProperty);
            set => SetValue(ItemsSourceProperty, value);
        }


        public List<FormattingRule> DefaultRules { get; set; } = new List<FormattingRule>();
        private bool _isLoading = false;

        private ICollectionView? _view;
        private string? _lastClickedValue;
        private DataGridColumn? _lastClickedColumn;

        public AdvancedDataGrid()
        {
            InitializeComponent();
            _filterDebounceTimer = new System.Windows.Threading.DispatcherTimer();
            _filterDebounceTimer.Interval = TimeSpan.FromMilliseconds(300);
            _filterDebounceTimer.Tick += FilterDebounceTimer_Tick;
            MainGrid.AutoGeneratingColumn += MainGrid_AutoGeneratingColumn;
            MainGrid.AutoGeneratedColumns += (s, e) => 
            {
                RestoreState();
                RefreshFilterRow();
            };
            this.Loaded += AdvancedDataGrid_Loaded;
            this.LayoutUpdated += (s, e) =>
            {
                // Force sync on layout update to ensure headers align
                if (FilterScrollViewer != null && MainGrid != null)
                {
                    var mainScrollViewer = FindVisualChild<ScrollViewer>(MainGrid);
                    if (mainScrollViewer != null && FilterScrollViewer.HorizontalOffset != mainScrollViewer.HorizontalOffset)
                    {
                        FilterScrollViewer.ScrollToHorizontalOffset(mainScrollViewer.HorizontalOffset);
                    }
                }
            };
            this.Unloaded += AdvancedDataGrid_Unloaded;

            FormattingRules.CollectionChanged += (s, e) => {
                RefreshGridStyles();
                // Auto-save on change
                SaveState();
            };
        }

        private void AdvancedDataGrid_Loaded(object sender, RoutedEventArgs e)
        {
            LoadState();
            var source = PresentationSource.FromVisual(this) as System.Windows.Interop.HwndSource;
            source?.AddHook(WndProc);
        }

        private void AdvancedDataGrid_Unloaded(object sender, RoutedEventArgs e)
        {
            SaveState();
            var source = PresentationSource.FromVisual(this) as System.Windows.Interop.HwndSource;
            source?.RemoveHook(WndProc);
        }

        private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            const int WM_MOUSEHWHEEL = 0x020E;
            if (msg == WM_MOUSEHWHEEL)
            {
                int delta = (short)((wParam.ToInt64() >> 16) & 0xFFFF);
                if (delta != 0)
                {
                    // Find the ScrollViewer inside the DataGrid
                    var scrollViewer = FindVisualChild<ScrollViewer>(MainGrid);
                    if (scrollViewer != null)
                    {
                        if (delta < 0)
                            scrollViewer.LineRight();
                        else
                            scrollViewer.LineLeft();
                        handled = true;
                    }
                }
            }
            return IntPtr.Zero;
        }

        private async void SaveState() => await InternalSaveStateAsync(PersistenceKey);

        private async Task InternalSaveStateAsync(string? key)
        {
            if (_isLoading || string.IsNullOrEmpty(key)) return;

            var state = new GridSessionState();


            state.FormattingRules = FormattingRules.ToList();

            foreach (var col in MainGrid.Columns)
            {
                if (col is DataGridBoundColumn bc && bc.Binding is Binding b)
                {
                    state.Columns.Add(new ColumnState
                    {
                        PropertyName = b.Path.Path,
                        Width = col.ActualWidth,
                        DisplayIndex = col.DisplayIndex,
                        IsVisible = col.Visibility == Visibility.Visible
                    });
                }
            }

            try
            {
                string dir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Config", "Layouts");
                Directory.CreateDirectory(dir);
                string path = Path.Combine(dir, $"{key}.json");
                string json = JsonSerializer.Serialize(state);
                await File.WriteAllTextAsync(path, json);
            }
            catch { }
        }

        private async void LoadState()
        {
            if (string.IsNullOrEmpty(PersistenceKey)) return;

            _isLoading = true;
            try
            {
                string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Config", "Layouts", $"{PersistenceKey}.json");
                
                GridSessionState? state = null;
                if (File.Exists(path))
                {
                    try 
                    {
                        string json = await File.ReadAllTextAsync(path);
                        state = JsonSerializer.Deserialize<GridSessionState>(json);
                    } catch { }
                }

                FormattingRules.Clear();
                
                if (state != null && state.FormattingRules != null)
                {
                    foreach (var r in state.FormattingRules) FormattingRules.Add(r);
                    _pendingState = state;
                }
                else if (DefaultRules != null)
                {
                    foreach (var r in DefaultRules) FormattingRules.Add(r);
                }
            }
            finally
            {
                _isLoading = false;
            }
        }

        private GridSessionState? _pendingState;

        private static void OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is AdvancedDataGrid control && e.NewValue is IEnumerable items)
            {
                control._view = CollectionViewSource.GetDefaultView(items);
                control._view.Filter = control.ExecuteFilter;
                control.MainGrid.ItemsSource = control._view;
                control.RefreshFilterRow();
            }
        }

        public static readonly DependencyProperty GlobalFilterTextProperty =
            DependencyProperty.Register("GlobalFilterText", typeof(string), typeof(AdvancedDataGrid), new PropertyMetadata(null, OnGlobalFilterTextChanged));

        public string GlobalFilterText
        {
            get => (string)GetValue(GlobalFilterTextProperty);
            set => SetValue(GlobalFilterTextProperty, value);
        }

        public static readonly DependencyProperty ColumnTypeIconProperty =
            DependencyProperty.RegisterAttached("ColumnTypeIcon", typeof(string), typeof(AdvancedDataGrid), new PropertyMetadata(null));

        public static void SetColumnTypeIcon(DataGridColumn element, string value) => element.SetValue(ColumnTypeIconProperty, value);
        public static string GetColumnTypeIcon(DataGridColumn element) => (string)element.GetValue(ColumnTypeIconProperty);

        public static readonly DependencyProperty IsColumnFilteredProperty =
            DependencyProperty.RegisterAttached("IsColumnFiltered", typeof(bool), typeof(AdvancedDataGrid), new PropertyMetadata(false));

        public static void SetIsColumnFiltered(DataGridColumn element, bool value) => element.SetValue(IsColumnFilteredProperty, value);
        public static bool GetIsColumnFiltered(DataGridColumn element) => (bool)element.GetValue(IsColumnFilteredProperty);

        private static void OnGlobalFilterTextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is AdvancedDataGrid control)
            {
                control._view?.Refresh();
                control.UpdateResultCount();
            }
        }

        public static readonly DependencyProperty ResultCountProperty =
            DependencyProperty.Register("ResultCount", typeof(int), typeof(AdvancedDataGrid), new PropertyMetadata(0));

        public int ResultCount
        {
            get { return (int)GetValue(ResultCountProperty); }
            set { SetValue(ResultCountProperty, value); }
        }

        private void UpdateResultCount()
        {
            if (_view == null)
            {
                ResultCount = 0;
                return;
            }

            // Optimize count if possible
            if (_view is CollectionView cv)
            {
                ResultCount = cv.Count;
            }
            else
            {
                int count = 0;
                foreach (var _ in _view) count++;
                ResultCount = count;
            }
        }




        private bool ExecuteFilter(object obj)
        {
            // 1. Check Global Filter
            bool matchesGlobal = true;
            if (!string.IsNullOrWhiteSpace(GlobalFilterText))
            {
                matchesGlobal = false;
                
                if (obj is DataRowView drv)
                {
                   // DataRowView is fast enough usually, but can be optimized if needed
                    foreach (var item in drv.Row.ItemArray)
                    {
                        if (item != null && (item.ToString() ?? "").Contains(GlobalFilterText, StringComparison.OrdinalIgnoreCase))
                        {
                            matchesGlobal = true;
                            break;
                        }
                    }
                }
                else
                {
                    // Optimization: Cache properties to avoid GetProperties() on every row
                    var type = obj.GetType();
                    if (!_propertyCache.TryGetValue(type, out var props))
                    {
                        props = type.GetProperties().Where(p => p.CanRead).ToArray();
                        _propertyCache[type] = props;
                    }

                    foreach (var prop in props)
                    {
                        var val = prop.GetValue(obj)?.ToString();
                        if (val != null && val.Contains(GlobalFilterText, StringComparison.OrdinalIgnoreCase))
                        {
                            matchesGlobal = true;
                            break;
                        }
                    }
                }
            }

            if (!matchesGlobal) return false;

            if (!matchesGlobal) return false;

            // 2. Check Column-Specific Filters (Text search and Distinct values)
            var objType = obj.GetType();
            
            // Text Search Filters
            if (_columnFilters.Count > 0 && !_columnFilters.Values.All(string.IsNullOrWhiteSpace))
            {
                foreach (var filter in _columnFilters)
                {
                    if (string.IsNullOrWhiteSpace(filter.Value)) continue;

                    string cellValue = GetCellValue(obj, filter.Key);
                    if (!cellValue.Contains(filter.Value, StringComparison.OrdinalIgnoreCase))
                        return false;
                }
            }

            // Distinct Value Filters
            if (_distinctFilters.Count > 0)
            {
                foreach (var filter in _distinctFilters)
                {
                    string cellValue = GetCellValue(obj, filter.Key);
                    if (string.IsNullOrEmpty(cellValue)) cellValue = "(Blanks)";
                    
                    if (!filter.Value.Contains(cellValue))
                        return false;
                }
            }

            // 3. Time Range Filter
            if (_activeTimeFilter != null)
            {
                DateTime? rowTime = null;
                
                // Ensure property name is valid
                if (string.IsNullOrEmpty(_activeTimeFilter.PropertyName)) return true;

                if (obj is DataRowView drv)
                {
                     if (drv.Row.Table.Columns.Contains(_activeTimeFilter.PropertyName))
                     {
                         var val = drv[_activeTimeFilter.PropertyName];
                         if (val != DBNull.Value)
                         {
                             if (val is DateTime dt) rowTime = dt;
                             else if (val is string s && DateTime.TryParse(s, out var parsed)) rowTime = parsed;
                         }
                     }
                }
                else
                {
                     // Optimization: Cache PropertyInfo
                     // Check nulls before comparing
                     if (_cachedTimePropertyName != _activeTimeFilter.PropertyName || _cachedTimeProperty == null)
                     {
                         _cachedTimePropertyName = _activeTimeFilter.PropertyName;
                         _cachedTimeProperty = obj.GetType().GetProperty(_activeTimeFilter.PropertyName);
                     }

                     if (_cachedTimeProperty != null)
                     {
                         var val = _cachedTimeProperty.GetValue(obj);
                          if (val != null)
                          {
                              if (val is DateTime dt) rowTime = dt;
                              else if (val is string s)
                              {
                                  // Try rigorous parsing
                                  if (DateTime.TryParse(s, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out var parsed))
                                      rowTime = parsed;
                                  else if (DateTime.TryParse(s, out parsed)) // Fallback to current culture
                                      rowTime = parsed;
                              }
                          }
                     }

                }

                if (rowTime.HasValue)
                {
                    // Check range
                    bool inRange = rowTime.Value >= _activeTimeFilter.Start && rowTime.Value <= _activeTimeFilter.End;
                    if (!inRange) return false;
                }
            }

            return true;
        }






        private TimeRangeEventArgs? _activeTimeFilter; // Can be null
        private System.Reflection.PropertyInfo? _cachedTimeProperty; // Can be null
        private string? _cachedTimePropertyName; // Can be null

        private string GetCellValue(object obj, string propertyName)
        {
            if (obj is DataRowView drv)
            {
                if (drv.Row.Table.Columns.Contains(propertyName))
                    return drv[propertyName]?.ToString() ?? "";
            }
            else
            {
                var prop = obj.GetType().GetProperty(propertyName);
                if (prop != null)
                {
                    return prop.GetValue(obj)?.ToString() ?? "";
                }
                else if (obj is IDictionary<string, object> dict && dict.ContainsKey(propertyName))
                {
                    return dict[propertyName]?.ToString() ?? "";
                }
            }
            return "";
        }

        private void TimelineChart_FilterChanged(object? sender, TimeRangeEventArgs? e)
        {
            _activeTimeFilter = e;
            _cachedTimeProperty = null; 
            _cachedTimePropertyName = null;

            _view?.Refresh();
        }

        private void TimelineChart_DateColumnChanged(object? sender, string propertyName)
        {
            // Default to Descending (Newest first)
            SortByColumn(propertyName, System.ComponentModel.ListSortDirection.Descending);
        }

        public void SortByColumn(string propertyName, System.ComponentModel.ListSortDirection direction)
        {
            if (_view == null) return;

            var column = MainGrid.Columns.FirstOrDefault(c => 
            {
                if (c is DataGridBoundColumn boundCol && boundCol.Binding is Binding binding)
                {
                    return binding.Path?.Path == propertyName;
                }
                return false;
            });

            using (_view.DeferRefresh())
            {
                _view.SortDescriptions.Clear();
                foreach (var c in MainGrid.Columns)
                {
                    c.SortDirection = null;
                }

                _view.SortDescriptions.Add(new System.ComponentModel.SortDescription(propertyName, direction));
                if (column != null)
                {
                    column.SortDirection = direction;
                }
            }
        }

        private void UserControl_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
        {
            // Enable Horizontal Scrolling with Shift+Wheel
            if (Keyboard.Modifiers == ModifierKeys.Shift)
            {
                e.Handled = true;
                // Find the ScrollViewer inside the DataGrid
                var scrollViewer = FindVisualChild<ScrollViewer>(MainGrid);
                if (scrollViewer != null)
                {
                    if (e.Delta < 0)
                        scrollViewer.LineRight();
                    else
                        scrollViewer.LineLeft();
                }
            }
        }

        private void MainGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            // Ensure we clicked a cell, not a header
            var hit = VisualTreeHelper.HitTest(MainGrid, e.GetPosition(MainGrid));
            if (hit != null)
            {
                var dep = hit.VisualHit;
                while (dep != null && !(dep is DataGridCell) && !(dep is DataGridColumnHeader))
                {
                    dep = VisualTreeHelper.GetParent(dep);
                }

                if (dep is DataGridCell)
                {
                    OpenValueViewer();
                }
            }
        }

        private void ViewValue_Click(object sender, RoutedEventArgs e)
        {
            OpenValueViewer();
        }

        private void OpenValueViewer()
        {
            if (MainGrid.CurrentCell == default || !MainGrid.CurrentCell.IsValid) return;

            var cellInfo = MainGrid.CurrentCell;
            var column = cellInfo.Column;
            var item = cellInfo.Item;

            if (column == null || item == null) return;

            try 
            {
                var content = column.GetCellContent(item);
                string text = "";

                if (content is TextBlock tb)
                {
                    text = tb.Text;
                }
                else if (content is ContentPresenter cp && cp.Content != null)
                {
                   text = cp.Content.ToString() ?? "";
                }
                else if (content != null)
                {
                    // Fallback: try to find a TextBlock inside
                    var childTb = FindVisualChild<TextBlock>(content);
                    if (childTb != null) text = childTb.Text;
                    else text = content.ToString() ?? "";
                }

                if (!string.IsNullOrEmpty(text))
                {
                    var viewer = new ValueViewer(text);
                    viewer.Owner = Window.GetWindow(this);
                    viewer.ShowDialog();
                }
            }
            catch (Exception)
            {
                // Fallback for complex virtualization scenarios or detached items
            }
        }

        private void MainGrid_ScrollChanged(object sender, ScrollChangedEventArgs e)
        {
            if (FilterScrollViewer != null)
            {
                FilterScrollViewer.ScrollToHorizontalOffset(e.HorizontalOffset);
            }
        }

        private void FilterDebounceTimer_Tick(object? sender, EventArgs e)
        {
            _filterDebounceTimer.Stop();
            _view?.Refresh();
            UpdateResultCount();
        }

        private void FilterTextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (sender is System.Windows.Controls.TextBox tb && tb.Tag is DataGridBoundColumn col && col.Binding is Binding binding && binding.Path != null)
            {
                var propertyName = binding.Path.Path ?? "";
                if (!string.IsNullOrEmpty(propertyName))
                {
                    _columnFilters[propertyName] = tb.Text;
                    UpdateColumnFilteredState(propertyName);
                    _filterDebounceTimer.Stop();
                    _filterDebounceTimer.Start();
                 }
            }
        }

        private void MainGrid_Sorting(object sender, DataGridSortingEventArgs e)
        {
            if (_view == null) return;

            e.Handled = true; // We'll handle sorting ourselves
            var column = e.Column;
            var direction = column.SortDirection == System.ComponentModel.ListSortDirection.Ascending ? System.ComponentModel.ListSortDirection.Descending : System.ComponentModel.ListSortDirection.Ascending;

            using (_view.DeferRefresh())
            {
                if ((System.Windows.Input.Keyboard.Modifiers & System.Windows.Input.ModifierKeys.Shift) != System.Windows.Input.ModifierKeys.Shift)
                {
                    _view.SortDescriptions.Clear();
                    foreach (var c in MainGrid.Columns)
                    {
                        if (c != column) c.SortDirection = null;
                    }
                }

                if (column is DataGridBoundColumn boundCol && boundCol.Binding is Binding binding)
                {
                    var propertyName = binding.Path?.Path;
                    if (propertyName == null) return; // Should not happen for bound columns

                    // Remove existing sort for this property if multi-sorting
                    var existing = _view.SortDescriptions.FirstOrDefault(sd => sd.PropertyName == propertyName);
                    if (existing != default) _view.SortDescriptions.Remove(existing);

                    _view.SortDescriptions.Add(new System.ComponentModel.SortDescription(propertyName, direction));
                    column.SortDirection = direction;
                }
            }
        }

        private void MainGrid_AutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            // Force valid width to ensure scrollbar activation
            // SizeToHeader might still be too small for short headers (like "ID"), so we use a strict minimum.
            e.Column.Width = 200;

            // Set Type Icon in Tag
            string typeIcon = "[abc]"; // Default to string
            var type = e.PropertyType;

            // ... (rest of type sniffing logic) ...


            // Type Sniffing for CSV/Untyped data
            if (type == typeof(string) && MainGrid.ItemsSource != null)
            {
                var firstItem = MainGrid.ItemsSource.Cast<object>().FirstOrDefault();
                if (firstItem != null)
                {
                    string? val = null;
                    if (firstItem is DataRowView drv)
                    {
                        val = drv[e.PropertyName]?.ToString();
                    }
                    else
                    {
                        val = firstItem.GetType().GetProperty(e.PropertyName)?.GetValue(firstItem)?.ToString();
                    }

                    if (!string.IsNullOrEmpty(val))
                    {
                        if (DateTime.TryParse(val, out _))
                        {
                            type = typeof(DateTime);
                            typeIcon = "[🕒]";
                        }
                        else if (long.TryParse(val, out _))
                        {
                            type = typeof(long);
                            typeIcon = "[123]";
                        }
                        else if (double.TryParse(val, out _))
                        {
                            type = typeof(double);
                            typeIcon = "[123]";
                        }
                    }
                }
            }
            else if (type == typeof(int) || type == typeof(long) || type == typeof(double) || type == typeof(decimal))
            {
                typeIcon = "[123]";
            }
            else if (type == typeof(DateTime))
            {
                typeIcon = "[🕒]";
            }
            
            SetColumnTypeIcon(e.Column, typeIcon);

            if (type == typeof(DateTime))
            {
                var column = e.Column as DataGridTextColumn;
                if (column != null && column.Binding is Binding binding && binding.Path != null)
                {
                    column.Binding.StringFormat = "yyyy-MM-dd HH:mm:ss.ffff";
                }
            }



            // Apply Highlighting Style to Text Columns
            if (e.Column is DataGridTextColumn textColumn)
            {
                try 
                {
                    textColumn.ElementStyle = this.FindResource("HighlightedTextBlockStyle") as Style;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"Error applying HighlightedTextBlockStyle: {ex.Message}");
                }
            }
        }

        private void RestoreState()
        {
            if (_pendingState == null) return;

            foreach (var col in MainGrid.Columns)
            {
                var saved = _pendingState.Columns.FirstOrDefault(c => c.PropertyName == col.SortMemberPath || c.PropertyName == col.Header.ToString());
                if (saved != null)
                {
                    // Restore width, but enforce minimum 200px to fix "squashed" saves
                    col.Width = Math.Max(saved.Width, 200);
                    col.DisplayIndex = Math.Min(saved.DisplayIndex, MainGrid.Columns.Count - 1);
                    col.Visibility = saved.IsVisible ? Visibility.Visible : Visibility.Collapsed;
                }
            }
            
            // Clear pending state after applying
            _pendingState = null; 
        }

        private void ColumnHeader_PreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
        {
            // Just swallow the down event so it doesn't trigger anything else (like focus shifts or cell context menus)
            if (sender is DataGridColumnHeader)
            {
                e.Handled = true;
            }
        }

        private void ColumnHeader_PreviewMouseRightButtonUp(object sender, MouseButtonEventArgs e)
        {
            if (sender is DataGridColumnHeader header)
            {
                OpenFilterForColumn(header.Column);
                e.Handled = true;
            }
        }

        private void HeaderFilter_Click(object sender, RoutedEventArgs e)
        {
            if (sender is Button btn)
            {
                var header = FindVisualParent<DataGridColumnHeader>(btn);
                if (header != null)
                {
                    OpenFilterForColumn(header.Column);
                }
            }
        }

        private void UpdateColumnFilteredState(string propertyName)
        {
            var column = MainGrid.Columns.FirstOrDefault(c => (c as DataGridBoundColumn)?.Binding is Binding b && b.Path?.Path == propertyName);
            if (column == null) return;

            bool hasTextFilter = _columnFilters.TryGetValue(propertyName, out var text) && !string.IsNullOrWhiteSpace(text);
            bool hasDistinctFilter = _distinctFilters.ContainsKey(propertyName);

            SetIsColumnFiltered(column, hasTextFilter || hasDistinctFilter);
        }

        private void OpenFilterForColumn(DataGridColumn gridColumn)
        {
            if (gridColumn is DataGridBoundColumn boundCol && boundCol.Binding is Binding binding)
            {
                var propertyName = binding.Path?.Path;
                if (string.IsNullOrEmpty(propertyName) || _view == null) return;

                _currentFilterProperty = propertyName;
                
                // Collect distinct values
                var distinctValues = new HashSet<string>();
                var source = _view.SourceCollection.Cast<object>();

                foreach (var item in source)
                {
                    string val = "";
                    if (item is DataRowView drv)
                    {
                        val = drv[propertyName]?.ToString() ?? "(Blanks)";
                    }
                    else
                    {
                        val = item.GetType().GetProperty(propertyName)?.GetValue(item)?.ToString() ?? "(Blanks)";
                    }
                    if (string.IsNullOrEmpty(val)) val = "(Blanks)";
                    distinctValues.Add(val);
                }

                var activeFilters = _distinctFilters.ContainsKey(propertyName) ? _distinctFilters[propertyName] : null;

                _currentDistinctItems = distinctValues.OrderBy(v => v).Select(v => new DistinctValueItem 
                { 
                    Value = v, 
                    IsChecked = activeFilters == null || activeFilters.Contains(v)
                }).ToList();

                DistinctValuesList.ItemsSource = _currentDistinctItems;
                
                _isUpdatingSelectAll = true;
                SelectAllCheckBox.IsChecked = _currentDistinctItems.All(i => i.IsChecked);
                _isUpdatingSelectAll = false;

                // Open the popup now that the mouse is UP
                DistinctFilterPopup.IsOpen = true;
                PopupBorder.Focus();
            }
        }

        private void MainGrid_ColumnReordered(object? sender, DataGridColumnEventArgs e)
        {
            RefreshFilterRow();
        }

        private void RefreshFilterRow()
        {
            if (MainGrid == null || FilterRow == null) return;

            // Sort columns by DisplayIndex to match visual order
            var sortedColumns = MainGrid.Columns.OrderBy(c => c.DisplayIndex).ToList();
            FilterRow.ItemsSource = sortedColumns;
        }

        private void MainGrid_ContextMenuOpening(object sender, ContextMenuEventArgs e)
        {
            // Reset captured state
            _lastClickedValue = null;
            _lastClickedColumn = null;

            var hitTestResult = VisualTreeHelper.HitTest(MainGrid, Mouse.GetPosition(MainGrid));
            if (hitTestResult != null)
            {
                // If it's a header, swallow the menu (already handled in PreviewMouseRightButtonUp)
                var header = FindVisualParent<DataGridColumnHeader>(hitTestResult.VisualHit);
                if (header != null)
                {
                    e.Handled = true;
                    return;
                }

                // If it's a cell, capture the value and column for the menu
                var cell = FindVisualParent<DataGridCell>(hitTestResult.VisualHit);
                if (cell != null)
                {
                    _lastClickedColumn = cell.Column;
                    var item = cell.DataContext;

                    if (cell.Column is DataGridBoundColumn boundCol && boundCol.Binding is Binding binding)
                    {
                        var propertyName = binding.Path?.Path;
                        if (!string.IsNullOrEmpty(propertyName))
                        {
                            if (item is DataRowView drv) _lastClickedValue = drv[propertyName]?.ToString();
                            else _lastClickedValue = item?.GetType().GetProperty(propertyName)?.GetValue(item)?.ToString();
                        }
                    }
                }
            }
        }

        private void CopyToClipboard_Click(object sender, RoutedEventArgs e)
        {
            if (!string.IsNullOrEmpty(_lastClickedValue))
            {
                Clipboard.SetText(_lastClickedValue);
            }
        }

        private void FilterForValue_Click(object sender, RoutedEventArgs e)
        {
            if (_lastClickedColumn != null && !string.IsNullOrEmpty(_lastClickedValue))
            {
                // Find the TextBox for this column in the FilterRow
                foreach (var item in FilterRow.Items)
                {
                    // The ItemTemplate for FilterRow uses the Column as the Context
                    var container = FilterRow.ItemContainerGenerator.ContainerFromItem(item) as FrameworkElement;
                    if (container != null)
                    {
                        var textBox = FindVisualChild<TextBox>(container);
                        if (textBox != null && textBox.Tag == _lastClickedColumn)
                        {
                            textBox.Text = _lastClickedValue; // This triggers FilterTextBox_TextChanged
                            break;
                        }
                    }
                }
            }
        }

        private T? FindVisualChild<T>(DependencyObject obj) where T : DependencyObject
        {
            for (int i = 0; i < VisualTreeHelper.GetChildrenCount(obj); i++)
            {
                var child = VisualTreeHelper.GetChild(obj, i);
                if (child is T t) return t;
                var childOfChild = FindVisualChild<T>(child);
                if (childOfChild != null) return childOfChild;
            }
            return null;
        }

        private T? FindVisualParent<T>(DependencyObject? child) where T : DependencyObject
        {
            while (child != null)
            {
                if (child is T parent) return parent;
                child = VisualTreeHelper.GetParent(child);
            }
            return null;
        }

        private void SelectAll_Checked(object sender, RoutedEventArgs e) => SetAllDistinct(true);
        private void SelectAll_Unchecked(object sender, RoutedEventArgs e) => SetAllDistinct(false);

        private void SetAllDistinct(bool isChecked)
        {
            if (_isUpdatingSelectAll) return;
            
            _isUpdatingSelectAll = true;
            try
            {
                foreach (var item in _currentDistinctItems) item.IsChecked = isChecked;
                UpdateDistinctFilter();
            }
            finally
            {
                _isUpdatingSelectAll = false;
            }
        }

        private void FilterCheck_Changed(object sender, RoutedEventArgs e)
        {
            if (_isUpdatingSelectAll) return;
            
            _isUpdatingSelectAll = true;
            try
            {
                // Update Select All state based on whether ANY are unchecked
                bool allChecked = _currentDistinctItems.All(i => i.IsChecked);
                if (SelectAllCheckBox.IsChecked != allChecked)
                {
                    SelectAllCheckBox.IsChecked = allChecked;
                }
                UpdateDistinctFilter();
            }
            finally
            {
                _isUpdatingSelectAll = false;
            }
        }

        private void UpdateDistinctFilter()
        {
            if (string.IsNullOrEmpty(_currentFilterProperty)) return;

            // Optimization: If everything is checked, we don't need a filter for this column
            bool allChecked = _currentDistinctItems.All(i => i.IsChecked);
            
            if (allChecked)
            {
                if (_distinctFilters.ContainsKey(_currentFilterProperty))
                    _distinctFilters.Remove(_currentFilterProperty);
            }
            else
            {
                var checkedItems = _currentDistinctItems.Where(i => i.IsChecked).Select(i => i.Value).ToHashSet();
                _distinctFilters[_currentFilterProperty] = checkedItems;
            }

            _view?.Refresh();
            UpdateResultCount();
        }

        private void ColumnHeader_PreviewMouseLeftButtonDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            _dragStartPoint = e.GetPosition(null);
        }

        private void ColumnHeader_MouseMove(object sender, System.Windows.Input.MouseEventArgs e)
        {
            Point mousePos = e.GetPosition(null);
            Vector diff = _dragStartPoint - mousePos;

            if (e.LeftButton == System.Windows.Input.MouseButtonState.Pressed &&
                (Math.Abs(diff.X) > SystemParameters.MinimumHorizontalDragDistance ||
                 Math.Abs(diff.Y) > SystemParameters.MinimumVerticalDragDistance))
            {
                if (sender is DataGridColumnHeader header)
                {
                    DragDrop.DoDragDrop(header, header, DragDropEffects.Link);
                }
            }
        }



        private void AddFormatting_Click(object sender, RoutedEventArgs e)
        {
            if (MainGrid.CurrentItem == null || MainGrid.CurrentColumn == null) return;

            var item = MainGrid.CurrentItem;
            var col = MainGrid.CurrentColumn;

            if (col is DataGridBoundColumn boundCol && boundCol.Binding is Binding binding)
            {
                var propertyName = binding.Path?.Path;
                if (propertyName == null) return;

                string cellValue = "";

                if (item is DataRowView drv)
                {
                    cellValue = drv[propertyName]?.ToString() ?? "";
                }
                else
                {
                    cellValue = item.GetType().GetProperty(propertyName)?.GetValue(item)?.ToString() ?? "";
                }

                if (!string.IsNullOrEmpty(cellValue))
                {
                    string colorHex = "#f7768e"; // Default
            if (sender is MenuItem mi)
            {
                // Prefer CommandParameter, fallback to Tag
                if (mi.CommandParameter != null)
                {
                    colorHex = mi.CommandParameter.ToString() ?? colorHex;
                }
                else if (mi.Tag != null)
                {
                    colorHex = mi.Tag.ToString() ?? colorHex;
                }
            }

                    var rule = new FormattingRule { PropertyName = propertyName ?? "", Value = cellValue, ColorHex = colorHex };
                    FormattingRules.Add(rule);
                    
                    // Force refresh grid styles
                    RefreshGridStyles();
                }
            }
        }

        private void RefreshGridStyles()
        {
            // Simple approach: re-trigger row loading or refresh view
            _view?.Refresh();
        }



        private void MainGrid_LoadingRow(object sender, DataGridRowEventArgs e)
        {
            var row = e.Row;
            var item = row.Item;
            row.ClearValue(Control.BackgroundProperty); // Reset to allow RowStyle to work

            foreach (var rule in FormattingRules)
            {
                string cellValue = "";
                if (item is DataRowView drv)
                {
                    var table = drv.Row.Table;
                    if (table.Columns.Contains(rule.PropertyName))
                    {
                        cellValue = drv[rule.PropertyName]?.ToString() ?? "";
                    }
                }
                else
                {
                    var prop = item.GetType().GetProperty(rule.PropertyName);
                    cellValue = prop?.GetValue(item)?.ToString() ?? "";
                }

                if (cellValue.Contains(rule.Value, StringComparison.OrdinalIgnoreCase))
                {
                    try
                    {
                        var color = (System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString(rule.ColorHex);
                        row.Background = new System.Windows.Media.SolidColorBrush(color) { Opacity = 0.6 };
                    }
                    catch { }
                    break;
                }
            }
        }

        private static readonly System.Windows.Media.Brush TransparentBrush = System.Windows.Media.Brushes.Transparent;


        private void OpenColumnChooser_Click(object sender, RoutedEventArgs e)
        {
            // Placeholder: Show/Hide columns
        }

        private void BestFitAll_Click(object sender, RoutedEventArgs e)
        {
            foreach (var column in MainGrid.Columns)
            {
                column.Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
            }
        }

        private void ExportExcel_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Export to XLSX coming soon!", "GlassDFIR");
        }

        private void ExportCsv_Click(object sender, RoutedEventArgs e)
        {
            ExportToCSV();
        }

        public void ExportToCSV()
        {
            if (_view == null) return;

            var sfd = new Microsoft.Win32.SaveFileDialog
            {
                Filter = "CSV Files (*.csv)|*.csv",
                FileName = $"{PersistenceKey}_Export_{DateTime.Now:yyyyMMdd_HHmm}.csv"
            };

            if (sfd.ShowDialog() == true)
            {
                try
                {
                    using (var writer = new StreamWriter(sfd.FileName))
                    {
                        var columns = MainGrid.Columns.OfType<DataGridBoundColumn>()
                            .Where(c => c.Visibility == Visibility.Visible)
                            .OrderBy(c => c.DisplayIndex)
                            .ToList();

                        // Headers
                        writer.WriteLine(string.Join(",", columns.Select(c => $"\"{c.Header}\"")));

                        // Data
                        foreach (var item in _view)
                        {
                            var values = new List<string>();
                            foreach (var col in columns)
                            {
                               var binding = col.Binding as Binding;
                               if (binding != null && binding.Path != null)
                               {
                                    string val = "";
                                    if (item is DataRowView drv) val = drv[binding.Path.Path]?.ToString() ?? "";
                                    else val = item.GetType().GetProperty(binding.Path.Path)?.GetValue(item)?.ToString() ?? "";
                                    values.Add($"\"{val.Replace("\"", "\"\"")}\"");
                               }
                            }
                            writer.WriteLine(string.Join(",", values));
                        }
                    }
                    MessageBox.Show("Export complete!", "GlassDFIR");
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Export failed: {ex.Message}", "Error");
                }
            }
        }
    }
}
